name: slack notification Test

# Triggers define when the workflow should run
on:
  # Trigger the workflow when code is pushed to the master branch
  push:
    branches:
      - main
    # Schedule the workflow to run daily at 00:30 AM UTC
  schedule:
    - cron: '30 0 * * *'
      # Allow manual execution of the workflow from the GitHub Actions tab
  workflow_dispatch:

# Define the jobs that should run when the workflow is triggered
jobs:
  # Define a job named 'build' that runs on an Ubuntu environment
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code repository
      - uses: actions/checkout@v2
      # Set up Java 11 using Temurin distribution
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      # Set up Maven with Java 11 and Temurin distribution
      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      # Compile the project using Maven
      - name: Compile Project
        run: mvn clean compile

      # Run tests using Maven
      - name: Run Tests
        run: mvn test -Dtest="com.testing.AppTest"

      # Generate test reports using Maven's surefire-report plugin
      - name: Generate Test Report
        run: |
          mvn surefire-report:report-only
          mvn site -DgenerateReports=false

      # Upload test report in GitHub
      - name: Upload Test Report Artifact
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-report
          path: target/site
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to warn

      - name: Parse Surefire Report
        id: parse-surefire-report
        run: |
          pass_count=$(grep -oP '<td></td>' target/site/surefire-report.html | wc -l)
          fail_count=$(grep -oP '<td></td>' target/site/surefire-report.html | wc -l)
          echo "::set-output name=pass_count::$pass_count"
          echo "::set-output name=fail_count::$fail_count"

      - name: Debug Surefire Report
        run: |
          cat target/site/surefire-report.html

      - name: Debug Parse Surefire Report
        run: |
          echo "Pass Count: ${{ steps.parse-surefire-report.outputs.pass_count }}"
          echo "Fail Count: ${{ steps.parse-surefire-report.outputs.fail_count }}"

      - name: Send Slack notification with Surefire report
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,commit,event,action,workflow,ref,url
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "#36a64f",
                  "title": "Surefire Report",
                  "text": "Passed tests: ${{ steps.parse-surefire-report.outputs.pass_count }}\nFailed tests: ${{ steps.parse-surefire-report.outputs.fail_count }}"
                }
              ]
            }
